version: "3"

services:
  speed-app:
    build:
      context: .
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    tty: true
